[tool.commitizen]
name = "cz_conventional_commits"
version = "0.6.1"
tag_format = "v$version"
version_files = [
    "pyproject.toml:version"
]
changelog_file = "CHANGELOG.md"
update_changelog_on_bump = true